server:
  port: 6001
spring:
  application:
    name: config-server-6001
  cloud:
    config:
      server:
        git:
          uri: https://github.com/better-a-little/spring-cloud-config-base/blob/master/config-server.yml
          username: 18626403370@163.com
          password: wangxf123456
