server:
  port: 6001
spring:
  application:
    name: config-server-6001
  cloud:
    config:
      server:
        git:
          uri: https://git/s.git
          search-paths:
          username:
          password: 
